// Generated by gencpp from file smarthome/ExecuteResponse.msg
// DO NOT EDIT!


#ifndef SMARTHOME_MESSAGE_EXECUTERESPONSE_H
#define SMARTHOME_MESSAGE_EXECUTERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smarthome
{
template <class ContainerAllocator>
struct ExecuteResponse_
{
  typedef ExecuteResponse_<ContainerAllocator> Type;

  ExecuteResponse_()
    : status()
    , error_code()  {
    }
  ExecuteResponse_(const ContainerAllocator& _alloc)
    : status(_alloc)
    , error_code(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_code_type;
  _error_code_type error_code;





  typedef boost::shared_ptr< ::smarthome::ExecuteResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smarthome::ExecuteResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ExecuteResponse_

typedef ::smarthome::ExecuteResponse_<std::allocator<void> > ExecuteResponse;

typedef boost::shared_ptr< ::smarthome::ExecuteResponse > ExecuteResponsePtr;
typedef boost::shared_ptr< ::smarthome::ExecuteResponse const> ExecuteResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smarthome::ExecuteResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smarthome::ExecuteResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smarthome::ExecuteResponse_<ContainerAllocator1> & lhs, const ::smarthome::ExecuteResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status &&
    lhs.error_code == rhs.error_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smarthome::ExecuteResponse_<ContainerAllocator1> & lhs, const ::smarthome::ExecuteResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smarthome

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smarthome::ExecuteResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smarthome::ExecuteResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smarthome::ExecuteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smarthome::ExecuteResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smarthome::ExecuteResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smarthome::ExecuteResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smarthome::ExecuteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90b1ebc3d52f1b5ba2a87e07b1130594";
  }

  static const char* value(const ::smarthome::ExecuteResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90b1ebc3d52f1b5bULL;
  static const uint64_t static_value2 = 0xa2a87e07b1130594ULL;
};

template<class ContainerAllocator>
struct DataType< ::smarthome::ExecuteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smarthome/ExecuteResponse";
  }

  static const char* value(const ::smarthome::ExecuteResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smarthome::ExecuteResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string status\n"
"string error_code\n"
;
  }

  static const char* value(const ::smarthome::ExecuteResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smarthome::ExecuteResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ExecuteResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smarthome::ExecuteResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smarthome::ExecuteResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status);
    s << indent << "error_code: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMARTHOME_MESSAGE_EXECUTERESPONSE_H
