// Generated by gencpp from file smarthome/Execute.msg
// DO NOT EDIT!


#ifndef SMARTHOME_MESSAGE_EXECUTE_H
#define SMARTHOME_MESSAGE_EXECUTE_H

#include <ros/service_traits.h>


#include <smarthome/ExecuteRequest.h>
#include <smarthome/ExecuteResponse.h>


namespace smarthome
{

struct Execute
{

typedef ExecuteRequest Request;
typedef ExecuteResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Execute
} // namespace smarthome


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::smarthome::Execute > {
  static const char* value()
  {
    return "f5558d63821155f2165fb31854f602ff";
  }

  static const char* value(const ::smarthome::Execute&) { return value(); }
};

template<>
struct DataType< ::smarthome::Execute > {
  static const char* value()
  {
    return "smarthome/Execute";
  }

  static const char* value(const ::smarthome::Execute&) { return value(); }
};


// service_traits::MD5Sum< ::smarthome::ExecuteRequest> should match
// service_traits::MD5Sum< ::smarthome::Execute >
template<>
struct MD5Sum< ::smarthome::ExecuteRequest>
{
  static const char* value()
  {
    return MD5Sum< ::smarthome::Execute >::value();
  }
  static const char* value(const ::smarthome::ExecuteRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::smarthome::ExecuteRequest> should match
// service_traits::DataType< ::smarthome::Execute >
template<>
struct DataType< ::smarthome::ExecuteRequest>
{
  static const char* value()
  {
    return DataType< ::smarthome::Execute >::value();
  }
  static const char* value(const ::smarthome::ExecuteRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::smarthome::ExecuteResponse> should match
// service_traits::MD5Sum< ::smarthome::Execute >
template<>
struct MD5Sum< ::smarthome::ExecuteResponse>
{
  static const char* value()
  {
    return MD5Sum< ::smarthome::Execute >::value();
  }
  static const char* value(const ::smarthome::ExecuteResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::smarthome::ExecuteResponse> should match
// service_traits::DataType< ::smarthome::Execute >
template<>
struct DataType< ::smarthome::ExecuteResponse>
{
  static const char* value()
  {
    return DataType< ::smarthome::Execute >::value();
  }
  static const char* value(const ::smarthome::ExecuteResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SMARTHOME_MESSAGE_EXECUTE_H
