// Generated by gencpp from file smarthome/Query.msg
// DO NOT EDIT!


#ifndef SMARTHOME_MESSAGE_QUERY_H
#define SMARTHOME_MESSAGE_QUERY_H

#include <ros/service_traits.h>


#include <smarthome/QueryRequest.h>
#include <smarthome/QueryResponse.h>


namespace smarthome
{

struct Query
{

typedef QueryRequest Request;
typedef QueryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Query
} // namespace smarthome


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::smarthome::Query > {
  static const char* value()
  {
    return "b9bd91a5b5d8aacd3cad48471a09f64a";
  }

  static const char* value(const ::smarthome::Query&) { return value(); }
};

template<>
struct DataType< ::smarthome::Query > {
  static const char* value()
  {
    return "smarthome/Query";
  }

  static const char* value(const ::smarthome::Query&) { return value(); }
};


// service_traits::MD5Sum< ::smarthome::QueryRequest> should match
// service_traits::MD5Sum< ::smarthome::Query >
template<>
struct MD5Sum< ::smarthome::QueryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::smarthome::Query >::value();
  }
  static const char* value(const ::smarthome::QueryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::smarthome::QueryRequest> should match
// service_traits::DataType< ::smarthome::Query >
template<>
struct DataType< ::smarthome::QueryRequest>
{
  static const char* value()
  {
    return DataType< ::smarthome::Query >::value();
  }
  static const char* value(const ::smarthome::QueryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::smarthome::QueryResponse> should match
// service_traits::MD5Sum< ::smarthome::Query >
template<>
struct MD5Sum< ::smarthome::QueryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::smarthome::Query >::value();
  }
  static const char* value(const ::smarthome::QueryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::smarthome::QueryResponse> should match
// service_traits::DataType< ::smarthome::Query >
template<>
struct DataType< ::smarthome::QueryResponse>
{
  static const char* value()
  {
    return DataType< ::smarthome::Query >::value();
  }
  static const char* value(const ::smarthome::QueryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SMARTHOME_MESSAGE_QUERY_H
