// Generated by gencpp from file smarthome/RegisterResponse.msg
// DO NOT EDIT!


#ifndef SMARTHOME_MESSAGE_REGISTERRESPONSE_H
#define SMARTHOME_MESSAGE_REGISTERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smarthome
{
template <class ContainerAllocator>
struct RegisterResponse_
{
  typedef RegisterResponse_<ContainerAllocator> Type;

  RegisterResponse_()
    : registered(false)  {
    }
  RegisterResponse_(const ContainerAllocator& _alloc)
    : registered(false)  {
  (void)_alloc;
    }



   typedef uint8_t _registered_type;
  _registered_type registered;





  typedef boost::shared_ptr< ::smarthome::RegisterResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smarthome::RegisterResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RegisterResponse_

typedef ::smarthome::RegisterResponse_<std::allocator<void> > RegisterResponse;

typedef boost::shared_ptr< ::smarthome::RegisterResponse > RegisterResponsePtr;
typedef boost::shared_ptr< ::smarthome::RegisterResponse const> RegisterResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smarthome::RegisterResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smarthome::RegisterResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smarthome::RegisterResponse_<ContainerAllocator1> & lhs, const ::smarthome::RegisterResponse_<ContainerAllocator2> & rhs)
{
  return lhs.registered == rhs.registered;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smarthome::RegisterResponse_<ContainerAllocator1> & lhs, const ::smarthome::RegisterResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smarthome

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smarthome::RegisterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smarthome::RegisterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smarthome::RegisterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smarthome::RegisterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smarthome::RegisterResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smarthome::RegisterResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smarthome::RegisterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91554a267ba7830695bdbe867d2fc3ef";
  }

  static const char* value(const ::smarthome::RegisterResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91554a267ba78306ULL;
  static const uint64_t static_value2 = 0x95bdbe867d2fc3efULL;
};

template<class ContainerAllocator>
struct DataType< ::smarthome::RegisterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smarthome/RegisterResponse";
  }

  static const char* value(const ::smarthome::RegisterResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smarthome::RegisterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool registered\n"
;
  }

  static const char* value(const ::smarthome::RegisterResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smarthome::RegisterResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.registered);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RegisterResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smarthome::RegisterResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smarthome::RegisterResponse_<ContainerAllocator>& v)
  {
    s << indent << "registered: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.registered);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMARTHOME_MESSAGE_REGISTERRESPONSE_H
