// Generated by gencpp from file smarthome/Register.msg
// DO NOT EDIT!


#ifndef SMARTHOME_MESSAGE_REGISTER_H
#define SMARTHOME_MESSAGE_REGISTER_H

#include <ros/service_traits.h>


#include <smarthome/RegisterRequest.h>
#include <smarthome/RegisterResponse.h>


namespace smarthome
{

struct Register
{

typedef RegisterRequest Request;
typedef RegisterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Register
} // namespace smarthome


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::smarthome::Register > {
  static const char* value()
  {
    return "362a90375ebbdf49f08adbcd6069ece9";
  }

  static const char* value(const ::smarthome::Register&) { return value(); }
};

template<>
struct DataType< ::smarthome::Register > {
  static const char* value()
  {
    return "smarthome/Register";
  }

  static const char* value(const ::smarthome::Register&) { return value(); }
};


// service_traits::MD5Sum< ::smarthome::RegisterRequest> should match
// service_traits::MD5Sum< ::smarthome::Register >
template<>
struct MD5Sum< ::smarthome::RegisterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::smarthome::Register >::value();
  }
  static const char* value(const ::smarthome::RegisterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::smarthome::RegisterRequest> should match
// service_traits::DataType< ::smarthome::Register >
template<>
struct DataType< ::smarthome::RegisterRequest>
{
  static const char* value()
  {
    return DataType< ::smarthome::Register >::value();
  }
  static const char* value(const ::smarthome::RegisterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::smarthome::RegisterResponse> should match
// service_traits::MD5Sum< ::smarthome::Register >
template<>
struct MD5Sum< ::smarthome::RegisterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::smarthome::Register >::value();
  }
  static const char* value(const ::smarthome::RegisterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::smarthome::RegisterResponse> should match
// service_traits::DataType< ::smarthome::Register >
template<>
struct DataType< ::smarthome::RegisterResponse>
{
  static const char* value()
  {
    return DataType< ::smarthome::Register >::value();
  }
  static const char* value(const ::smarthome::RegisterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SMARTHOME_MESSAGE_REGISTER_H
