// Generated by gencpp from file smarthome/Sync.msg
// DO NOT EDIT!


#ifndef SMARTHOME_MESSAGE_SYNC_H
#define SMARTHOME_MESSAGE_SYNC_H

#include <ros/service_traits.h>


#include <smarthome/SyncRequest.h>
#include <smarthome/SyncResponse.h>


namespace smarthome
{

struct Sync
{

typedef SyncRequest Request;
typedef SyncResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Sync
} // namespace smarthome


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::smarthome::Sync > {
  static const char* value()
  {
    return "48480747096164cd9f8f89c8b4be064a";
  }

  static const char* value(const ::smarthome::Sync&) { return value(); }
};

template<>
struct DataType< ::smarthome::Sync > {
  static const char* value()
  {
    return "smarthome/Sync";
  }

  static const char* value(const ::smarthome::Sync&) { return value(); }
};


// service_traits::MD5Sum< ::smarthome::SyncRequest> should match
// service_traits::MD5Sum< ::smarthome::Sync >
template<>
struct MD5Sum< ::smarthome::SyncRequest>
{
  static const char* value()
  {
    return MD5Sum< ::smarthome::Sync >::value();
  }
  static const char* value(const ::smarthome::SyncRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::smarthome::SyncRequest> should match
// service_traits::DataType< ::smarthome::Sync >
template<>
struct DataType< ::smarthome::SyncRequest>
{
  static const char* value()
  {
    return DataType< ::smarthome::Sync >::value();
  }
  static const char* value(const ::smarthome::SyncRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::smarthome::SyncResponse> should match
// service_traits::MD5Sum< ::smarthome::Sync >
template<>
struct MD5Sum< ::smarthome::SyncResponse>
{
  static const char* value()
  {
    return MD5Sum< ::smarthome::Sync >::value();
  }
  static const char* value(const ::smarthome::SyncResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::smarthome::SyncResponse> should match
// service_traits::DataType< ::smarthome::Sync >
template<>
struct DataType< ::smarthome::SyncResponse>
{
  static const char* value()
  {
    return DataType< ::smarthome::Sync >::value();
  }
  static const char* value(const ::smarthome::SyncResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SMARTHOME_MESSAGE_SYNC_H
